feat: add jina deployment support
jina-ai/jcloud pull request #170
Opened 2023-09-22 14:30 UTC by subbuv26

**Goal**
--------
Add support for all the below operations for Jina Deployment
- [x] list
- [x] remove
- [x] update
- [x] restart
- [x] pause
- [x] resume
- [x] scale
- [x] recreate
- [x] status
- [x] deploy
- [x] logs

----------------

- [x] Run [Integration tests GHA](https://github.com/jina-ai/jcloud/actions/workflows/integration-tests.yml) manually & comment the link. 👉 https://github.com/jina-ai/jcloud/actions/runs/6508262154

@jina-ai/team-wolf

2023-09-25 07:23 UTC, npitsillos requested changes
Some minor comments on using a generic function for when an error occurs.

2023-09-25 07:23 UTC, npitsillos commented on jcloud/deployment.py
> +def _exit_if_response_error(
This also exists in `jcloud/flow.py` can we remove this and use a generic one?

2023-09-25 07:23 UTC, npitsillos commented on jcloud/deployment.py
> +def print_server_response(error_message: str):
Same as above

2023-09-29 16:21 UTC, npitsillos approved these changes

2023-10-11 02:42 UTC, tarrantro approved these changes
lgtm

2023-10-11 02:46 UTC, tarrantro commented on jcloud/parsers/update.py
> +    # TODO (subbu) need make flow to be optional as deployment can be used instead of flow
what is deployment can be used instead of flow?

2023-10-13 14:55 UTC, merged