feat(normalize): add `jc normalize` flow
jina-ai/jcloud pull request #95
Opened 2022-11-21 15:28 UTC by npitsillos

**Goal**

- [ ] Run [Integration tests GHA](https://github.com/jina-ai/jcloud/actions/workflows/integration-tests.yml) manually & comment the link.

@jina-ai/team-wolf

2022-11-23 10:13 UTC, npitsillos commented
In this PR I am also simplifying the `_get_post_params()` logic. See screenshots below.
### Before
![image](https://user-images.githubusercontent.com/9141826/203521001-64c84374-79c6-40e0-9b64-868ad1c946b5.png)

### After
![image (1)](https://user-images.githubusercontent.com/9141826/203521136-a7c97667-5c3e-478a-860a-d3fb34a5f95a.png)

2022-11-24 09:35 UTC, deepankarm requested changes
Minor comment

2022-11-24 09:35 UTC, deepankarm commented on jcloud/normalize_helper.py
> +import os
Please rename this file to `normalize.py`

2022-11-24 10:26 UTC, npitsillos commented
### Running `jc normalize <path>`
![image](https://user-images.githubusercontent.com/9141826/203760048-b9b65aee-ffa2-472f-a526-288c281f3470.png)

### Running `jc deploy <path>`
![image](https://user-images.githubusercontent.com/9141826/203760720-b198ae27-42d0-4af6-865a-82d68806123d.png)

2022-11-24 12:28 UTC, deepankarm approved these changes
Great work :+1:

2022-11-28 06:15 UTC, merged